version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: Chat_Test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres_test:/var/lib/postgresql/data
#      - ./data/init_scripts:/docker-entrypoint-initdb.d
